[project]
name = "projeto-final-poo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Sandenberg Ferreira Melo" }]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.0",
    "fastapi[standard]>=0.115.6",
    "pydantic-settings>=2.7.1",
    "rich>=13.9.4",
    "sqlalchemy>=2.0.37",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.1",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
dev = 'fastapi dev src/projeto_final_poo/app.py'
start = 'fastapi run src/projeto_final_poo/app.py'

lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff format .'

migrate_upgrade = 'alembic upgrade head'
migrate_generate = 'alembic revision --autogenerate -m'
migrate = 'task migrate_generate'
post_migrate = 'task migrate_upgrade'

seed = 'uv run src/projeto_final_poo/db/seed.py'
clean = 'rm -rf .pytest_cache .coverage htmlcov'

coverage = 'coverage html'
pre_test = 'task lint'
test = 'pytest --cov=projeto_final_poo -vv'
post_test = 'task coverage'
pre_test_only = 'task lint'
test_only = 'pytest -vv'

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
