name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Copy files from repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: 'uv-cache'

      - name: Instalar dependências
        run: uv sync

      - name: Executar testes
        run: uv run task test_only
